using System;
using UnityEngine;

/// <summary>
/// Applies a held-out Platt/logit calibration model to a raw observation score.
/// The fitted JSON must be produced from calibration episodes, never from test episodes.
/// </summary>
[DisallowMultipleComponent]
public sealed class ReliabilityCalibrator : MonoBehaviour
{
    [Serializable]
    private class CalibrationParameters
    {
        public int schema_version = 1;
        public bool is_fitted = false;
        public string calibration_id = "UNFITTED";
        public string fitted_split = "";
        public int sample_count = 0;
        public float logit_scale = 1f;
        public float logit_bias = 0f;
        public float write_threshold = 0.25f;
        public float verify_threshold = 0.45f;
        public float pursue_threshold = 0.75f;
        public int minimum_independent_confirmations = 1;
        public float independent_view_distance = 1.5f;
        public float independent_view_angle = 25f;
    }

    [Header("Held-out calibration")]
    [Tooltip("Assign JSON generated by Experiments/fit_reliability_calibrator.py.")]
    public TextAsset parametersAsset;

    [Tooltip("Useful only for debugging. Formal D-method runs must use a fitted asset.")]
    public bool allowIdentityFallbackForDebug = false;

    [SerializeField] private string loadStatus = "not loaded";
    private CalibrationParameters parameters = new CalibrationParameters();

    public bool IsFitted
    {
        get { return parametersAsset != null && parameters != null && parameters.is_fitted; }
    }

    public bool IsUsable
    {
        get { return IsFitted || allowIdentityFallbackForDebug; }
    }

    public string CalibrationId
    {
        get { return parameters != null ? parameters.calibration_id : "UNLOADED"; }
    }

    public string FittedSplit
    {
        get { return parameters != null ? parameters.fitted_split : ""; }
    }

    public int SampleCount
    {
        get { return parameters != null ? parameters.sample_count : 0; }
    }

    public float WriteThreshold { get { return parameters.write_threshold; } }
    public float VerifyThreshold { get { return parameters.verify_threshold; } }
    public float PursueThreshold { get { return parameters.pursue_threshold; } }
    public int MinimumIndependentConfirmations
    {
        get { return Mathf.Max(1, parameters.minimum_independent_confirmations); }
    }
    public float IndependentViewDistance
    {
        get { return Mathf.Max(0.1f, parameters.independent_view_distance); }
    }
    public float IndependentViewAngle
    {
        get { return Mathf.Clamp(parameters.independent_view_angle, 1f, 180f); }
    }

    private void Awake()
    {
        Reload();
    }

    private void OnValidate()
    {
        Reload();
    }

    public bool Reload()
    {
        parameters = new CalibrationParameters();
        if (parametersAsset == null)
        {
            loadStatus = "no JSON assigned; identity fallback";
            return false;
        }

        try
        {
            CalibrationParameters loaded = JsonUtility.FromJson<CalibrationParameters>(parametersAsset.text);
            if (loaded == null || loaded.schema_version != 1)
            {
                loadStatus = "invalid or unsupported schema";
                return false;
            }
            parameters = loaded;
            loadStatus = parameters.is_fitted
                ? "fitted: " + parameters.calibration_id + " (n=" + parameters.sample_count + ")"
                : "template is not fitted";
            return parameters.is_fitted;
        }
        catch (Exception error)
        {
            loadStatus = "parse error: " + error.Message;
            parameters = new CalibrationParameters();
            return false;
        }
    }

    public float Calibrate(float rawScore)
    {
        float clipped = Mathf.Clamp(rawScore, 0.0001f, 0.9999f);
        if (!IsFitted) return Mathf.Clamp01(rawScore);

        double logit = Math.Log(clipped / (1.0 - clipped));
        double transformed = parameters.logit_scale * logit + parameters.logit_bias;
        if (transformed >= 0.0)
        {
            double z = Math.Exp(-transformed);
            return (float)(1.0 / (1.0 + z));
        }
        else
        {
            double z = Math.Exp(transformed);
            return (float)(z / (1.0 + z));
        }
    }
}
